#!/bin/bash

BASE=${1:-5900}
INCR=0

while true
do
	PORT=$((BASE + INCR))
	
	ACT1=$(lsof -i -n -P | grep -E ":${PORT} " | cut -f 2 -d: | cut -f 1 -d- )
	ACT2=$(for i in $(awk '{print $2}' /proc/net/tcp | cut -f 2 -d:); do perl -e "print hex \"$i\",\"\\n\";"; done | grep ^${PORT})

	if [ -z "${ACT1}" -a -z "${ACT2}" ]
	then
		echo "${PORT}"
		exit 1
	fi
	
	INCR=$((INCR + 1))
done
